const bancoDeCartas = [
    { pistas: ["Sou irmã de Arão. (Ex 15:20)", "Fui seguida por todas as mulheres tocando tambores em louvor ao Senhor. (Ex 15:20-21)", "Apresentei Joquebede à filha do Faraó para amamentar seu filho Moisés. (Ex 2:5-10)", "Por falar contra meu irmão fiquei leprosa. (Nm 12:5-10)"], resposta: "Miriã", castigo: "imitar um avião decolando" },
    { pistas: ["O profeta João Batista se vestia igual a mim. (2 Rs 1:7-8)", "Matei 450 falsos profetas e em seguida me escondi por temer uma mulher. (1 Rs 18:22 e 19:1-4)", "Fui alimentado duas vezes por um anjo do Senhor. (1 Rs 19:5-7)", "Fui arrebatado em um carro com cavalos de fogo. (2 Rs 2:11)"], resposta: "Elias", castigo: "imitar um gatinho bebendo leite" },
    { pistas: ["Mardoqueu me adotou como filha. (Et 2:7)", "Por minha causa Hamã foi enforcado na forca que ele mesmo construiu. (Et 7:1-10)", "Depois que Hamã foi enforcado ganhei a sua casa. (Et 8:1)", "Estabeleci a festa do Purim. (Et 9:25-32)"], resposta: "Ester", castigo: "fazer uma careta" },
    { pistas: ["Eu era um pecador e Jesus me salvou. (Lc 19:7-9)", "A multidão me impediu de ver a Jesus. (Lc 19:3)", "Fui chefe dos cobradores de impostos. (Lc 19:2)", "Jesus dormiu em minha casa. (Lc 19:5)"], resposta: "Zaqueu", castigo: "abraçar o oponente que estiver vencendo" },
    { pistas: ["Eu provoquei a ira de Deus mais do que todos os reis de Israel. (1 Rs 16:33)", "Sou filho do rei Onri. (1 Rs 16:30)", "Eu reinei sobre Israel e Samaria por 22 anos. (1 Rs 16:29)", "Fui marido de Jezabel. (1 Rs 21:25)"], resposta: "Acabe", castigo: "imitar uma borboleta" },
    { pistas: ["Meu filho morreu em meus braços com uma forte dor de cabeça. (2 Rs 4:19-20)", "Após ressuscitar, meu filho espirrou sete vezes. (2 Rs 4:19-20)", "Mandei construir e mobiliar um quarto para hospedar um santo homem de Deus. (2 Rs 4:8-10)", "Repreendi o profeta Eliseu pela morte de meu filho. (2 Rs 4:27-28)"], resposta: "Mulher Sunamita", castigo: "imitar o rei Davi tocando harpa" },
    { pistas: ["Não me contaminei com a comida nem com a bebida do rei da Babilônia. (Dn 1:1,8)", "Satanás impediu por 21 dias que o anjo Gabriel respondesse minha oração. (Dn 10:12-15)", "Fui jovem de boa aparência e instruído em sabedoria. (Dn 1:3-6)", "Por orar ao meu Deus fui lançado na cova dos leões. (Dn 6:11-17)"], resposta: "Daniel", castigo: "imitar um pintinho batendo asas" },
    { pistas: ["Deus usou um monstro como exemplo para me exortar. (Jó cap: 41)", "Minha oração livrou meus três amigos da morte. (Jó 42:7-9)", "Deus permitiu que Satanás devastasse minha vida. (Jó 2:1-10)", "Minha mulher sugeriu que eu amaldiçoasse a Deus e eu a repreendi. (Jó 2:9-10)"], resposta: "Jó", castigo: "imitar uma moto dando partida" }
];